### ISSUE TITLE
How to upgrade nextcloud?

### ISSUE THREAD

**Issue by klundry** [uboslinux/ubos-nextcloud#14]
Does it get upgraded when running ubos-admin update?  If so what is the update timeline?  I am on NC 12.0.0 with ubos.  2 releases have been made since then (12.0.1 & 12.0.2) and the arch repo is on 12.0.2.

**Comment by jernst** [comment]
As long as we are in beta, we release app and os upgrades at the same time every couple of months to whatever is current at that time. Once we are out of beta, we will probably release apps on a faster schedule than os so we can track upstream app upgrades, but that is tbd.

So currently, you have two choices:
1. Wait for the next UBOS beta, which will have an upgraded Nextcloud like so many other things
2. Upgrade Nextcloud yourself (which is work for you, and a certain risk -- but would be nice for us if you contributed your changes back to UBOS). To to that, git clone the ubos-nextcloud repo, increment the version in PKGBUILD, makepkg, install the resulting package on a test UBOS device, ubos-admin createsite or deploy on the test device and make sure everything works as it should. If not, fix what needs fixing :-) Ultimately, upgrade your production device with the new package using ubos-admin update --pkg <new package>. If everything still works, check your changes into github and issue a pull request, which we'd appreciate!

**Comment by jernst** [comment]
Upgraded.
