### ISSUE TITLE
Nextcloud 5.0.5 warning messages

### ISSUE THREAD

**Issue by jernst** [uboslinux/ubos-nextcloud#41]
> Your web server is not properly set up to resolve "/ocm-provider/". This is most likely related to a web server configuration that was not updated to deliver this folder directly. Please compare your configuration against the shipped rewrite rules in ".htaccess" for Apache or the provided one in the documentation for Nginx at it's documentation page. On Nginx those are typically the lines starting with "location ~" that need an update.
> Your web server is not properly set up to resolve "/ocs-provider/". This is most likely related to a web server configuration that was not updated to deliver this folder directly. Please compare your configuration against the shipped rewrite rules in ".htaccess" for Apache or the provided one in the documentation for Nginx at it's documentation page. On Nginx those are typically the lines starting with "location ~" that need an update.

**Comment by jernst** [comment]
It appears these messages are only emitted when running Nextcloud at a context path that's not at the top of the site.

**Comment by MorrisJobke** [comment]
> * deployed to `/next`:
>   
>   * GET (curl, no cookies) on `/next/ocm-provider/` redirects to `/next/login` (302 Found)
>   * GET (curl, no cookies) on `/next/ocs-provider/` produces JSON content (200 OK)
>   * GET (browser, after logon) on Administration / Overview / Security & setup warnings: The warnings in the original content of this issue
> * deployed to :
>   
>   * GET (curl, no cookies) on `/next/ocm-provider/` redirects to `/next/login` (302 Found)
>   * GET (curl, no cookies) on `/next/ocs-provider/` produces JSON content (200 OK)
>   * GET (browser, after logon) on Administration / Overview / Security & setup warnings: None

I can't see the difference in the two deployment results. Could you highlight them? Because they only differ in the result, but not in the state.

**Comment by jernst** [comment]
The difference is the warnings produced. If the GETs on `.../oc...` indeed behave the same, why would the Administration / Overview / Security & setup warnings be different?

**Comment by MorrisJobke** [comment]
> The difference is the warnings produced. If the GETs on `.../oc...` indeed behave the same, why would the Administration / Overview / Security & setup warnings be different?

This is most likely that one of them is on a different version. We introduced this check in the latest minor release, because there was a missing line in the .htaccess. The 

> * GET (curl, no cookies) on `/next/ocm-provider/` redirects to `/next/login` (302 Found)

That one is actually indicating that the configuration is wrong. It should return a 200 return code if the web server is configured correctly.

See the changes in https://github.com/nextcloud/server/pull/14312/files#diff-71e73fda1689de129cac998f80a812a8 for Apache or the ones in https://github.com/nextcloud/documentation/pull/1260/files for Nginx.

cc @tflidd @rakekniven once this question comes up in the forums as well.

**Comment by jernst** [comment]
* I found that I had not tracked recent updates to the `.htaccess` file correctly. Fixed, so now both endpoints return JSON.
* However, the real reason why the self-check report errors at a non-empty context path, according to what I see in Network debug mode of my browser, is that it checks against `/ocX-provider`, not `/next/ocX-provider` if Nextcloud is deployed at `/next`.

I don't know why this is. (Is there documentation somewhere?) It could be because:
* something is wrong with the check, it should be checking `/next/ocXprovider` or relative to whatever the installation context path is.
* installation of Nextcloud at non-root context paths is not supported any more.
* installation of Nextcloud at non-root context paths is supported, as long as `/osXprovider` is mapped into the namespace at the site without the prefix.

Clarification appreciated.

**Comment by MorrisJobke** [comment]
> * However, the real reason why the self-check report errors at a non-empty context path, according to what I see in Network debug mode of my browser, is that it checks against `/ocX-provider`, not `/next/ocX-provider` if Nextcloud is deployed at `/next`.
> 
> I don't know why this is. (Is there documentation somewhere?) It could be because:

This is because of the specification of the OpenCloudMesh. A standard to make cloud federation possible. The /ocm-provider path below the root domain is there to detect if a service supports this. This is similar to the `/.well-known` stuff that is there to detect the usage of given client side capabilities.

**Comment by jernst** [comment]
Hey @MorrisJobke, I appreciate you bearing with me here.

Given what you are saying, I suggest:

* clearly documenting that if installing Nextcloud on a context path other than root, some functionality (open cloud mesh) currently will not be functional. (This may be documented somewhere, but at least I have not seen it, so perhaps it needs to be more prominent in the flow of the primary installation instructions)
* Thinking through, and coming up with a recommendation, how a hypothetical organization `example.com` should design their DNS/context path name space to optimally host their public-facing web apps. It appears to me that they would want `example.com` to be a public website (say, running Wordpress) with marketing info, contact, product info, as companies do. But now, particulary since Nextcloud has "social", chances are Nextcloud should also run at that hostname, so users can engage from `@user@example.com` ... redirects to `nextcloud.example.com` would be not so great IMHO. (If so, that would mean perhaps nextcloud should run at `example.com/nextcloud`, so it doesn't conflict with Wordpress etc, but the `/ocX...` members of the namespace should be mapped to the root. Which would require different instructions for `.htaccess` files etc. Perhaps those could simply be redirects to `/nextcloud/osX...`? That'd be easier to implement.)

(Again, I may be all wrong about how this is intended to work ... but, immodest as I am, I simply assume that if I am wrong, so will be others and we'd rather not anybody be wrong :-) )

**Comment by MorrisJobke** [comment]
> * clearly documenting that if installing Nextcloud on a context path other than root, some functionality (open cloud mesh) currently will not be functional. (This may be documented somewhere, but at least I have not seen it, so perhaps it needs to be more prominent in the flow of the primary installation instructions)

In general this is what the setup checks are for. Sure we can add more information there, but it actually is properly detected, that this URL was not working as we intended it. Mind to open an issue in the server repo with the error message and how it could be improved from your point of view=



> * Thinking through, and coming up with a recommendation, how a hypothetical organization `example.com` should design their DNS/context path name space to optimally host their public-facing web apps. It appears to me that they would want `example.com` to be a public website (say, running Wordpress) with marketing info, contact, product info, as companies do. But now, particulary since Nextcloud has "social", chances are Nextcloud should also run at that hostname, so users can engage from `@user@example.com` ... redirects to `nextcloud.example.com` would be not so great IMHO. (If so, that would mean perhaps nextcloud should run at `example.com/nextcloud`, so it doesn't conflict with Wordpress etc, but the `/ocX...` members of the namespace should be mapped to the root. Which would require different instructions for `.htaccess` files etc. Perhaps those could simply be redirects to `/nextcloud/osX...`? That'd be easier to implement.)

This is a whole other story that we already have a longer discussion in the social app repo and the server repo. Handling all of this is unfortunately not that easy and should be discussed in those repos.

**Comment by jernst** [comment]
Ok, I filed an issue over at /nextcloud/server. Can close this.
