### ISSUE TITLE
Nextcloud app doesn't set up HSTS

### ISSUE THREAD

**Issue by Bugsbane** [uboslinux/ubos-nextcloud#6]
After installing Nextcooud10 with the UBOS Virtualbox machine, Nextcloud gives the following security warning in the admin section:

> The "Strict-Transport-Security" HTTP header is not configured to at least "15552000" seconds. For enhanced security we recommend enabling HSTS as described in our [security tips](https://files.piersduruz.com/index.php/settings/admin/tips-tricks).

Really this should be set up, either to begin with or when Nextcloud is installed.

**Comment by jernst** [comment]
This apparently is accomplished by adding to the htaccess fragement:

```
<IfModule mod_headers.c>
  Header always set Strict-Transport-Security "max-age=15768000; includeSubDomains; preload"
</IfModule>
```
(see https://docs.nextcloud.com/server/9/admin_manual/configuration_server/harden_server.html#enable-hsts-label)

However, only if the app runs at a TLS-enabled site. So we'd have to generate the htaccess fragment in a script that checks whether it's https or http, and depending on that, generates that additional fragment or not.
