### ISSUE TITLE
Nextcloud app doesn't set up memcaching

### ISSUE THREAD

**Issue by Bugsbane** [uboslinux/ubos-nextcloud#7]
After installing Nextcloud10 on the VIrtualbox image of UBOS, the Nextcloud admin section warns that:

> No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our [documentation.](https://docs.nextcloud.org/server/10/go.php?to=admin-performance)

It would help if caching was set up automatically when an app that would use it is installed.

**Comment by jernst** [comment]
https://docs.nextcloud.com/server/11/admin_manual/configuration_server/caching_configuration.html
